version: '3'

services:
  voting.api:
    image: votingapi
    build:
      context: .
      dockerfile: Voting.API/Dockerfile
    environment:
      REDIS: votingdb
      RABBITMQ: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password

  voting.processor:
    image: votingprocessor
    build:
      context: .
      dockerfile: Voting.Processor/Dockerfile
    environment:
      REDIS: votingdb
      RABBITMQ: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password

  voting.webpy:
    image: votingwebpy
    build:
      context: ./Voting.Webpy/
      dockerfile: Dockerfile    
    environment:
      LOCAL: ""
      API_ADDRESS: "voting.api"
    ports:
        - "8080:5000"