version: '3'

services:
  voting.web:
    image: votingweb
    build:
      context: .
      dockerfile: Voting.Web/Dockerfile
    environment:
      - Option1=Tabs
      - Option1=Spaces
      - votes-api-address=voting.api

  voting.api:
    image: votingapi
    build:
      context: .
      dockerfile: Voting.API/Dockerfile
    environment:
      REDIS: votingdb
      RABBITMQ: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password

  voting.processor:
    image: votingprocessor
    build:
      context: .
      dockerfile: Voting.Processor/Dockerfile
    environment:
      REDIS: votingdb
      RABBITMQ: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password

  voting.webpy:
    image: votingwebpy
    build:
      context: ./Voting.Webpy/
      dockerfile: Dockerfile    
    environment:
      LOCAL: ""
    ports:
        - "8080:80"

  voting.db:
    image: redis
    container_name: votingdb
    ports:
        - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"